/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardShowRouteImport } from './routes/_dashboard/show'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/_dashboard/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardShowRoute = DashboardShowRouteImport.update({
  id: '/_dashboard/show',
  path: '/show',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/show': typeof DashboardShowRoute
  '/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/show': typeof DashboardShowRoute
  '/': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_dashboard/show': typeof DashboardShowRoute
  '/_dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/signin' | '/signup' | '/show' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/signin' | '/signup' | '/show' | '/'
  id: '__root__' | '/signin' | '/signup' | '/_dashboard/show' | '/_dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  DashboardShowRoute: typeof DashboardShowRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/show': {
      id: '/_dashboard/show'
      path: '/show'
      fullPath: '/show'
      preLoaderRoute: typeof DashboardShowRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  DashboardShowRoute: DashboardShowRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
