/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as _dashboardIndexRouteImport } from './routes/__dashboard/index'
import { Route as _dashboardShowRouteImport } from './routes/__dashboard/show'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const _dashboardIndexRoute = _dashboardIndexRouteImport.update({
  id: '/__dashboard/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const _dashboardShowRoute = _dashboardShowRouteImport.update({
  id: '/__dashboard/show',
  path: '/show',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/show': typeof _dashboardShowRoute
  '/': typeof _dashboardIndexRoute
}
export interface FileRoutesByTo {
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/show': typeof _dashboardShowRoute
  '/': typeof _dashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/__dashboard/show': typeof _dashboardShowRoute
  '/__dashboard/': typeof _dashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/signin' | '/signup' | '/show' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/signin' | '/signup' | '/show' | '/'
  id: '__root__' | '/signin' | '/signup' | '/__dashboard/show' | '/__dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  _dashboardShowRoute: typeof _dashboardShowRoute
  _dashboardIndexRoute: typeof _dashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__dashboard/': {
      id: '/__dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _dashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__dashboard/show': {
      id: '/__dashboard/show'
      path: '/show'
      fullPath: '/show'
      preLoaderRoute: typeof _dashboardShowRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  _dashboardShowRoute: _dashboardShowRoute,
  _dashboardIndexRoute: _dashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
