[package]
name = "link_crawler"
version = "0.1.0"
authors = ["Diptesh Choudhuri <ignisda2001@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.14.10"
html5ever = "0.21.0"
url = "0.2.37"
