version: "3.8"

services:
  development-machine:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    container_name: learning

    volumes:
      - ..:/workspace/learning:cached
      - postgres_data:/var/lib/postgresql/data

    command: sleep infinity

volumes:
  postgres_data:
