version: "3.8"

services:
  development-machine:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    container_name: learning

    volumes:
      - ..:/workspace/learning:cached

    command: sleep infinity
