#!/usr/bin/env bash
# This script will be used to install dependencies for all the fictitious applications

# remove the default fish shell prompt
set fish_greeting

# load all my system configs
sudo rm -rf $HOME/.config
git clone https://github.com/IgnisDa/linux-configs.git $HOME/.config
sudo chown -R $USERNAME:$USERNAME $HOME/.config

# setup the git identities
git config --global user.name "$GIT_AUTHOR_NAME"
git config --global user.email "$GIT_AUTHOR_EMAIL"
